name: CICD

on: 
  workflow_dispatch:
    inputs:
      enviroments:
        description: This is the environments value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - pro
          - staging

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code clone from GitHub"

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build docker container
        run: echo "Docker container build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test the container
        run: echo "Testing the container"

  deploy:
    if: inputs.enviroments == 'dev'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
