name: Portfolio

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # Upload static site files
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # This uploads your root folder (index.html)

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4